services:
  bot:
    build: .
    volumes:
      # TODO This should probably be turned into a database table instead.
      - ./blacklist.json:/opt/python-bot/blacklist.json
      # Persistent database folder for any file based databases we may use.
      - database:/opt/python-bot/database:rw
    environment:
      BOT_PREFIX: !
      BOT_TOKEN: UNSET_TOKEN
      BOT_OWNERS: UNSET_OWNER_IDS SEPARATED_BY_SPACE
      BOT_DATABASE_FILE_LOCATION: /opt/python-bot/database/dog_bot.db
      BOT_BLACKLIST_FILE_LOCATION: /opt/python-bot/blacklist.json
      BOT_CONFIG_FILE_LOCATION: /opt/python-bot/blacklist.json
    # Use the internal image variables when determining what to pass to the command ($$).
    command: [ "--prefix", "$$BOT_PREFIX",
               "--token", "$$BOT_TOKEN",
               "--owners", "$$BOT_OWNERS",
               "--database_file_location", "$$BOT_DATABASE_FILE_LOCATION",
               "--blacklist_file_location", "$$BOT_BLACKLIST_FILE_LOCATION",
               "--config_file_location", "$$BOT_CONFIG_FILE_LOCATION" ]

# Create a volume that will persist through restarts for our database.
volumes:
  database: